"""HTML timeline report generator for ReplayLab.

Produces a self-contained HTML file showing the recovery timeline
with before/after metrics — useful for judge presentations and sharing.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ReplayLab Recovery Report</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }
.container { max-width: 900px; margin: 0 auto; }
h1 { color: #58a6ff; margin-bottom: 0.5rem; font-size: 1.8rem; }
.subtitle { color: #8b949e; margin-bottom: 2rem; }
.timeline { position: relative; padding-left: 2rem; }
.timeline::before { content: ''; position: absolute; left: 0.75rem; top: 0; bottom: 0; width: 2px; background: #30363d; }
.step { position: relative; margin-bottom: 1.5rem; padding: 1rem 1.5rem; background: #161b22; border: 1px solid #30363d; border-radius: 8px; }
.step::before { content: ''; position: absolute; left: -1.65rem; top: 1.2rem; width: 12px; height: 12px; border-radius: 50%; }
.step.fail::before { background: #f85149; }
.step.diagnose::before { background: #d29922; }
.step.fix::before { background: #58a6ff; }
.step.success::before { background: #3fb950; }
.step-title { font-weight: 600; margin-bottom: 0.5rem; }
.step.fail .step-title { color: #f85149; }
.step.diagnose .step-title { color: #d29922; }
.step.fix .step-title { color: #58a6ff; }
.step.success .step-title { color: #3fb950; }
.metric { display: inline-block; background: #21262d; padding: 0.3rem 0.7rem; border-radius: 4px; margin: 0.2rem 0.3rem 0.2rem 0; font-family: monospace; font-size: 0.85rem; }
.comparison { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-top: 1.5rem; }
.card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; }
.card h3 { font-size: 0.9rem; margin-bottom: 0.5rem; }
.card.bad { border-color: #f85149; }
.card.good { border-color: #3fb950; }
.card.bad h3 { color: #f85149; }
.card.good h3 { color: #3fb950; }
.footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #8b949e; font-size: 0.8rem; }
code { background: #21262d; padding: 0.5rem 0.8rem; border-radius: 4px; display: block; overflow-x: auto; font-size: 0.85rem; margin-top: 0.5rem; white-space: pre-wrap; }
</style>
</head>
<body>
<div class="container">
<h1>ReplayLab Recovery Report</h1>
<p class="subtitle">GPU experiment flight recorder — failure to recovery timeline</p>

<div class="timeline">
  <div class="step fail">
    <div class="step-title">FAILURE DETECTED</div>
    <p>{{FAIL_SUMMARY}}</p>
    <div style="margin-top:0.5rem">
      <span class="metric">batch_size: {{BAD_BATCH}}</span>
      <span class="metric">memory: {{BAD_MEMORY}} MB</span>
      <span class="metric">exit_code: {{BAD_EXIT}}</span>
    </div>
  </div>

  <div class="step diagnose">
    <div class="step-title">DIAGNOSIS</div>
    <p>{{DIAGNOSIS_TEXT}}</p>
    <div style="margin-top:0.5rem">
      <span class="metric">cause: {{CAUSE}}</span>
      <span class="metric">confidence: {{CONFIDENCE}}</span>
    </div>
  </div>

  <div class="step fix">
    <div class="step-title">REPLAY COMMAND</div>
    <p>{{FIX_TEXT}}</p>
    <code>{{REPLAY_COMMAND}}</code>
  </div>

  <div class="step success">
    <div class="step-title">RECOVERY VERIFIED</div>
    <p>{{SUCCESS_SUMMARY}}</p>
    <div style="margin-top:0.5rem">
      <span class="metric">batch_size: {{GOOD_BATCH}}</span>
      <span class="metric">memory: {{GOOD_MEMORY}} MB</span>
      <span class="metric">throughput: {{GOOD_THROUGHPUT}}</span>
    </div>
  </div>
</div>

<div class="comparison">
  <div class="card bad">
    <h3>Failed Run</h3>
    <span class="metric">batch_size: {{BAD_BATCH}}</span>
    <span class="metric">memory_pressure: True</span>
    <span class="metric">throughput: 0</span>
    <span class="metric">exit_code: {{BAD_EXIT}}</span>
  </div>
  <div class="card good">
    <h3>Recovered Run</h3>
    <span class="metric">batch_size: {{GOOD_BATCH}}</span>
    <span class="metric">memory_pressure: False</span>
    <span class="metric">throughput: {{GOOD_THROUGHPUT}}</span>
    <span class="metric">exit_code: 0</span>
  </div>
</div>

<div class="footer">
  <p>Generated by ReplayLab | AMD Developer Hackathon 2026 | GPU experiment recovery agent</p>
</div>
</div>
</body>
</html>"""


def generate_report(
    bad_metrics: dict[str, Any],
    good_metrics: dict[str, Any],
    diagnosis: dict[str, Any],
    fix: dict[str, Any],
    output_path: str | Path = "replaylab/runs/report.html",
) -> Path:
    """Generate an HTML timeline report from run data."""
    bad_batch = bad_metrics.get("batch_size", "?")
    bad_memory = bad_metrics.get("estimated_memory_mb", "?")
    bad_exit = 1 if bad_metrics.get("memory_pressure") else 0
    good_batch = good_metrics.get("batch_size", "?")
    good_memory = good_metrics.get("estimated_memory_mb", "?")
    throughput = good_metrics.get("throughput_items_per_sec", 0)
    good_throughput = f"{throughput/1000:.0f}k items/sec" if throughput >= 1000 else f"{throughput} items/sec"

    cause = diagnosis.get("cause", "unknown")
    confidence = diagnosis.get("confidence", "high")
    explanation = diagnosis.get("explanation", "Memory pressure from oversized batch size.")
    recommended_fix = diagnosis.get("recommended_fix", f"Reduce batch_size from {bad_batch} to {good_batch}")

    replay_command = fix.get("fixed_command", "python replaylab/demo/demo_experiment.py --config replaylab/demo/config_good.json --output replaylab/runs/replay")

    html = TEMPLATE
    html = html.replace("{{FAIL_SUMMARY}}", f"Run failed with batch_size={bad_batch}, estimated memory {bad_memory} MB exceeds available.")
    html = html.replace("{{BAD_BATCH}}", str(bad_batch))
    html = html.replace("{{BAD_MEMORY}}", str(bad_memory))
    html = html.replace("{{BAD_EXIT}}", str(bad_exit))
    html = html.replace("{{DIAGNOSIS_TEXT}}", explanation)
    html = html.replace("{{CAUSE}}", cause)
    html = html.replace("{{CONFIDENCE}}", str(confidence))
    html = html.replace("{{FIX_TEXT}}", recommended_fix)
    html = html.replace("{{REPLAY_COMMAND}}", replay_command)
    html = html.replace("{{SUCCESS_SUMMARY}}", f"Recovered run succeeded with batch_size={good_batch}.")
    html = html.replace("{{GOOD_BATCH}}", str(good_batch))
    html = html.replace("{{GOOD_MEMORY}}", str(good_memory))
    html = html.replace("{{GOOD_THROUGHPUT}}", good_throughput)

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    return out
